# Generated by Django 5.0.3 on 2024-04-03 03:24

from django.db import migrations
from django.contrib.auth.models import User



def generate_user_name(apps, schema_editor):
    for user in User.objects.all():
        user.first_name = user.username
        user.save()
    

class Migration(migrations.Migration):

    dependencies = [
        ("training", "0003_reward_userreward"),
    ]


    operations = [migrations.RunPython(generate_user_name),]
