# Generated by Django 5.0.3 on 2024-04-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0004_flll_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="reward",
            name="score_to_unlock",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
