# Generated by Django 5.0.3 on 2024-04-03 04:08

from django.db import migrations


def generate_rewards(apps, schema_editor):
    Reward = apps.get_model("training", "Reward")

    rewards = [
        {"name": "Python Tshirt", "description": "A third party Python Tshirt will be given", "score_to_unlock": 200},
        {"name": "Apple watch", "description": "Brand new apple watch", "score_to_unlock": 5000},
        {"name": "Iphone 14", "description": "Brand new iphone to be given", "score_to_unlock": 10000},
    ]

    for reward_data in rewards:
        Reward.objects.create(**reward_data)


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0005_reward_score_to_unlock"),
    ]

    operations = [migrations.RunPython(generate_rewards),]
